volumes:
  server_node_modules:
  client_node_modules:
services:
  server:
    build:
      context: ./server
    container_name: server
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
    container_name: client
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - "5173:5173"
