volumes:
  app_node_modules:
services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    ports:
      - "3000:3000"


